name: lung_cancer_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - seaborn
  - pyspark
  - pymongo
  - pytest
  - pytest-mock
  - pip
  - pip:
      - urllib3
      - pytest-notebook
